### ISSUE TITLE
Support for raw data from http://www.keyboard-layout-editor.com

### ISSUE THREAD

**Issue by Supermagnum** [burabure/dactyl-keyboard#2]
I think that support for raw data from the mentioned page should be implemented.
I dont understand Clojure at all.

A example :
http://www.keyboard-layout-editor.com/#/gists/c881b4af35745d286a7193ede6e3d1f9

**Comment by burabure** [comment]
firmware repo is https://github.com/burabure/qmk_firmware/tree/master/keyboards/dactyl_manuform

this is the 3d model repo

**Comment by Supermagnum** [comment]
This has nothing to do with the firmware.
Its about adding the capability to read code from the mentioned page.
![ergo](https://user-images.githubusercontent.com/4554462/90409389-5f3ab800-e0a9-11ea-939e-d0130d0ce094.png)
The code for the keyboard layout above is:
["Esc",{x:0.25},"F1",{x:0.25},"F2",{x:0.25},"F3",{x:0.25},"F4",{x:0.25},"F5",{x:0.25},"F6",{x:2.5},"F7",{x:0.25},"F9",{x:0.25},"F10",{x:0.25},"F11",{x:0.25},"F12",{x:0.25},"Print Screen",{x:0.25},"Scroll lock"],
[{y:0.25,x:3.5},"3",{x:10.5},"\\"],
[{y:-0.87,x:2.5},"2",{x:1},"4",{x:8.5},"+",{x:1},"`"],
[{y:-0.88,x:5.5},"5","6","7",{x:2.5},"8","9","0"],
[{y:-0.87,fa:[1],w:1.5},"§\n\n\n\n\n\n|",{f:3},"1",{x:14.5,a:7},"",{a:4,f:3,w:1.5},"Backspace"],
[{y:-0.38,x:3.5,f:3},"E",{x:10.5,f:3},"P"],
[{y:-0.87,x:2.5,f:3},"W",{x:1,f:3},"R",{x:8.5,f:3},"O",{x:1,f:3},"Å"],
[{y:-0.88,x:5.5,f:3},"T",{f:3},"Y",{f:3,h:1.5},"Insert",{x:2.5,f:3,h:1.5},"Home",{f:3},"U",{f:3},"I"],
[{y:-0.87,f:3,w:1.5},"Tab",{f:3},"Q",{x:14.5,f:3},"^\n\"",{x:0.25,a:6,f:3,w:1.25,h:2,w2:1.5,h2:1,x2:-0.25},"Enter"],
[{y:-0.38,x:3.5,a:4,f:3},"D",{x:10.5,f:3},"Ø"],
[{y:-0.87,x:2.5,f:3},"S",{x:1,f:3},"F",{x:8.5,f:3},"L",{x:1,f:3},"Æ"],
[{y:-0.88,x:5.5,f:3},"G",{f:3},"H",{x:4.5,f:3},"J",{f:3},"K"],
[{y:-0.87,f:3,w:1.5},"Caps\n\n\n\n\n\nLock",{f:3},"A",{x:14.5,f:3},"*"],
[{y:-0.63,x:7.5,f:3,h:1.5},"Delete",{x:2.5,f:3,h:1.5},"End"],
[{y:-0.75,x:3.5,f:3},"X",{x:10.5,f:3},":"],
[{y:-0.87,x:2.5,f:3},"Z",{x:1,f:3},"C",{x:8.5,f:3},";",{x:1,f:3},"_"],
[{y:-0.88,x:5.5,f:3},"V",{f:3},"B",{x:4.5,f:3},"N",{f:3},"M"],
[{y:-0.87,f:3,w:1.5},"Shift",{f:3},">",{x:14.5,a:7},"",{a:4,f:3,w:1.5},"Shift"],
[{y:-0.38,x:3.5,a:7},"",{x:10.5,a:4,f:3},"Page Down"],
[{y:-0.87,x:2.5,f:3},"Alt",{x:1,f:3},"L1\nL2",{x:8.5,f:3},"Page Up",{x:1,f:3},"Alt Gr"],
[{y:-0.75,x:0.5,f:3},"Ctrl",{a:7},"",{x:14.5,a:4,f:3},"FN",{f:3},"Ctrl"],
[{r:30,rx:6.75,ry:4,y:1.75,x:1.5,a:7},""],
[{x:0.5},"","",""],
[{r:-30,rx:13,ry:4.25,y:1.5,x:-2.5},""],
[{x:-3.5},"","",""]

That should be obvious translated in to the necessary format, so clojure can read it.
It should make it easier to use for those like me who does not understand how to program, and at least not something that obscure like clojure.

**Comment by Supermagnum** [comment]
He understood me:
https://github.com/jaredjennings/dactyl-keyboard/issues/60
